CREATE TABLE IF NOT EXISTS synchronize (
    idsynchronize BIGINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    switchone BOOLEAN NOT NULL DEFAULT FALSE,
    switchtwo BOOLEAN NOT NULL DEFAULT FALSE,
    switchthree BOOLEAN NOT NULL DEFAULT FALSE,
    switchfour BOOLEAN NOT NULL DEFAULT FALSE
) DEFAULT CHARACTER SET utf8, engine=InnoDB;

CREATE TABLE IF NOT EXISTS users (
    idusers BIGINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    password TEXT NOT NULL
) DEFAULT CHARACTER SET utf8, engine=InnoDB;

CREATE TABLE IF NOT EXISTS logs (
    idlogs BIGINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    logtype ENUM('login', 'control') NOT NULL,
    message TEXT NOT NULL
) DEFAULT CHARACTER SET utf8, engine=InnoDB;